### ISSUE TITLE
CRAN version outdates

### ISSUE THREAD

**Issue by LukasBDF** [tomaskrehlik/fftSpillover#4]
The CRAN version of the package still loads version 0.1.6

**Comment by tomaskrehlik** [comment]
Thanks for reminder, will update the CRAN version promptly.


On 10 November 2017 at 14:56:05, LukasBDF (notifications@github.com) wrote:

The CRAN version of the package still loads version 0.1.6

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomaskrehlik/frequencyConnectedness/issues/4>, or mute
the thread

**Comment by LukasBDF** [comment]
Great, much appreciated!

**Comment by MikeJonessss** [comment]
dear thomas, i notice that still version 0.1.6 is loaded from CRAN. also the functions are different in the CRAN version compared to your readme in this repository. thank you!

**Comment by tomaskrehlik** [comment]
New version was submitted to CRAN waiting for approval.
